routes.py
from flask import Blueprint, render_template, session, redirect, request, send_file
from flask_login import login_required, login_user,logout_user, current_user
from werkzeug.security import generate_password_hash, check_password_hash
from uuid import uuid4
from datetime import datetime, timedelta
from models import db, User, PasswordResetToken
from fuctions import send_forget_password_mail

routes = Blueprint('route', __name__)

@routes.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'GET':
        if session.get('skipped_login'): session['skipped_login'] = False
        if current_user.is_authenticated: return redirect('/')
        return render_template('login.html')
    else:
        if request.form.get('skip-login'):
            session['skipped_login'] = True
            return redirect('/')
        
        email = request.form.get('email')
        password = request.form.get('password')

        error_messages = {}
        if not email: error_messages['email'] = "Enter a valid email"
        if not password: error_messages['password'] = "Enter a valid password"
        if len(password)<5: error_messages['password'] = "Password is too short. Please choose a password that is at least 6 characters long."
        if len(error_messages) != 0: return render_template('login.html', error_messages=error_messages)

        user = User.query.filter_by(email=email).first()
        if not user or not check_password_hash(user.password, password):
            error_messages['error'] = "Please check your login details and try again."
            return render_template('login.html', error_messages=error_messages)
        
        session['skipped_login'] = False
        login_user(user, remember=True)
        return redirect('/')

    
@routes.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'GET':
        if session.get('skipped_login'): session['skipped_login'] = False
        if current_user.is_authenticated: return redirect('/')
        return render_template('register.html')
    else:
        name = request.form.get('name')
        email = request.form.get('email')
        password = request.form.get('password')

        error_messages = {}

        if not name: error_messages['name'] = "Enter a valid name"
        if not email: error_messages['email'] = "Enter a valid email"
        if not password: error_messages['password'] = "Enter a valid password"
        if password and len(password)<5: error_messages['password'] = "Password is too short. Please choose a password that is at least 6 characters long."

        user = User.query.filter_by(email=email).first()
        if user: error_messages['email'] = 'Email address already exists'

        if len(error_messages) != 0: return render_template('register.html', error_messages=error_messages)

        new_user = User(email=email, name=name, password=generate_password_hash(password))
        db.session.add(new_user)
        db.session.commit()
        login_user(new_user, remember=True)
        return redirect('/')

@routes.route('/forget-password', methods=['GET', 'POST'])
def forget_password():
    if request.method == 'GET':
        if current_user.is_authenticated: return redirect('/')
        return render_template('forget-password.html')
    else:
        email = request.form.get('email')
        if not email: 
            return render_template('forget-password.html', error_messages={'email': "Enter a valid email"})
        
        user = User.query.filter_by(email=email).first()
        if not user:
            return render_template('forget-password.html', error_messages={'error': "There is no user exist with this email"})
        
        password_reset_token = PasswordResetToken.query.filter_by(user_id=user.id).first()
        token = str(uuid4()).replace('-', '')[:32]
        if not password_reset_token:
            password_reset_token = PasswordResetToken(token=token, user_id=user.id)
        else:
            if (datetime.now() - password_reset_token.date) < timedelta(minutes=15):
                return render_template('forget-password.html', error_messages={'error': "Password reset link sent to your email. Please check your inbox, and spam folder if needed, to complete the process."})
            password_reset_token.token = token
            password_reset_token.date = datetime.now()
        db.session.add(password_reset_token)
        db.session.commit()

        email_sent = send_forget_password_mail(user.email, token)
        return render_template('forget-password.html', email_sent=email_sent)
        
@routes.route('/change-password', methods=['GET', 'POST'])
def change_password():
    if request.method == 'GET':
        if current_user.is_authenticated or request.args.get('token'):
            return render_template('change-password.html')
        return redirect('/')
    else:
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')
        if not password1 or len(password1) < 5:
            return render_template('change-password.html', error_messages={'error': "Password is too short. Please choose a password that is at least 6 characters long."})
        if password1 != password2:
            return render_template('change-password.html', error_messages={'error': "Password doesn't matched"})
        if current_user.is_authenticated:
            current_user.password = generate_password_hash(password1)
            db.session.commit()
            return render_template('change-password.html', password_updated=True)
        else:
            token = request.args.get('token')
            password_reset_token = PasswordResetToken.query.filter_by(token=token).first()
            if not password_reset_token:
                return render_template('change-password.html', error_messages={'error': "Invalid Token!"})
            if (datetime.now() - password_reset_token.date) >= timedelta(hours=24):
                return render_template('change-password.html', error_messages={'error': "Password Reset Token is expired!"})
            user = User.query.filter_by(id=password_reset_token.user_id).first()
            user.password = generate_password_hash(password1)
            db.session.delete(password_reset_token)
            db.session.commit()
            return redirect('/login')


@routes.route('/logout')
def logout():
    logout_user()
    if session.get('skipped_login'): session.clear()
    return redirect('/')

@routes.route('/')
@routes.route('/home')
def index():
    users = User.query.order_by(User.high_score.desc()).all()
    if current_user.is_authenticated or session.get('skipped_login'):
        position = None
        if current_user.is_authenticated:
            position = users.index(current_user)
        top3users = None
        if len(users) > 3:
            top3users = users[:3]
            users = users[3:]
        print(top3users)
        return render_template('index.html', top3users=top3users, users=users, position=position)
    else:
        return redirect('/login')    

@login_required
@routes.route('/profile', methods=['GET', 'POST'])
def profile():
    if not current_user.is_authenticated:
        return redirect('/login')
    if request.method == 'GET':
        return render_template('profile.html')
    else:
        if 'profile_picture' in request.files and request.files['profile_picture']:
            photo = request.files['profile_picture']
            photo_path = f'uploads/profiles/user_{current_user.id}.{photo.filename.split(".")[-1]}'
            photo.save(photo_path)
            current_user.profile_picture = '/' + photo_path
        
        name = request.form.get('name')
        if name:
            current_user.name = name
            if len(name) < 3:
                return render_template('profile.html', error_messages={'name': 'Enter a valid name'})
        email = request.form.get('email')
        if email:
            current_user.email = email
            if len(email) < 10:
                return render_template('profile.html', error_messages={'email': 'Enter a valid email'})

        db.session.add(current_user)
        db.session.commit()
        return render_template('profile.html')


@routes.route('/about')
def about():
    return render_template('about.html')

@routes.route('/contact')
def contact():
    return render_template('contact.html')

from os.path import join as join_path
@routes.route('/uploads/profiles/<file_name>')
def download_file(file_name):
    return send_file(join_path('uploads/profiles/', file_name))

templates/about.html
{% extends 'base.html' %}
{% block title %}Login{% endblock %}

{% block content %}

<div class="content">
    <divs style="max-width: 600px; text-align: center; position: relative;">
        <h1>About Us</h1>
        <p style="padding-top: 20px;">
            Welcome to the "About Us" page, where the story of our collaborative endeavor unfolds. We are a passionate
            team
            of four individuals who joined forces to bring the "MemoryMastermind" to life. Hailing from the
            prestigious 'R.D.S College Muz.' under the umbrella of B.R.A.B.U, our shared academic journey paved the way
            for a shared vision of innovation.
        </p>
        <div>
            <h2 style="padding: 30px 0px 10px 0px;">Meet the minds behind the project</h2>
            <p>Shubham Kumar</p>
            <p>Ritu Raj</p>
            <p>Surendra Kumar</p>
            <p>Ravi Kumar</p>
        </div>
</div>

</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}{% endblock %}</title>
    {% block stylesheets %}
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}" />
    {% endblock %}
</head>

<body>
    <header>
        <div class="logo">
            <img src="{{ url_for('static', filename='assets/logo.png')}}" alt="" h>
            <h2 class="logo">MemoryMastermind</h2>
        </div>
        <nav class="navigation">
            {% if request.url_rule | string() != '/'%}
            <a href="/" class="nav-item">Home</a>
            {% endif %}
            <a href="/about" class="nav-item">About</a>
            <a href="/contact" class="nav-item">Contact Us</a>
            {% if current_user.is_anonymous and request.url_rule | string() == '/' %}
            <a href="/login" class="login-button">Login</a>
            {% elif current_user.is_authenticated and request.url_rule | string() != '/profile'%}
            <a href="/profile">
                <img class="nav-user-photo"
                    src="{% if current_user.profile_picture %}{{ current_user.profile_picture }}{% else %}{{ url_for('static', filename='assets/default-profile.png')}}{% endif %}"
                    alt="" srcset="">
            </a>
            {% elif current_user.is_authenticated and request.url_rule | string() == '/profile'%}
            <a href="/logout" class="logout-button">Logout</a>
            {% endif %}
        </nav>
    </header>
    {% block content %}
    {% endblock %}

</body>
{% block scripts %}
{% endblock %}

</html>

templates/change-password.html
{% extends 'base.html' %}
{% block title %}Change Password{% endblock %}

{% block content %}

<div class="form-page">
    {% if password_updated %}
    <div class="form-success">
        <svg fill="#000000" class="icon" version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg"
            xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 512 512" xml:space="preserve">
            <g>
                <path d="M474.045,173.813c-4.201,1.371-6.494,5.888-5.123,10.088c7.571,23.199,11.411,47.457,11.411,72.1
		c0,62.014-24.149,120.315-68,164.166s-102.153,68-164.167,68s-120.316-24.149-164.167-68S16,318.014,16,256
		S40.149,135.684,84,91.833s102.153-68,164.167-68c32.889,0,64.668,6.734,94.455,20.017c28.781,12.834,54.287,31.108,75.81,54.315
		c3.004,3.239,8.066,3.431,11.306,0.425c3.24-3.004,3.43-8.065,0.426-11.306c-23-24.799-50.26-44.328-81.024-58.047
		C317.287,15.035,283.316,7.833,248.167,7.833c-66.288,0-128.608,25.813-175.48,72.687C25.814,127.392,0,189.712,0,256
		c0,66.287,25.814,128.607,72.687,175.479c46.872,46.873,109.192,72.687,175.48,72.687s128.608-25.813,175.48-72.687
		c46.873-46.872,72.687-109.192,72.687-175.479c0-26.332-4.105-52.26-12.201-77.064
		C482.762,174.736,478.245,172.445,474.045,173.813z" />
                <path d="M504.969,83.262c-4.532-4.538-10.563-7.037-16.98-7.037s-12.448,2.499-16.978,7.034l-7.161,7.161
		c-3.124,3.124-3.124,8.189,0,11.313c3.124,3.123,8.19,3.124,11.314-0.001l7.164-7.164c1.51-1.512,3.52-2.344,5.66-2.344
		s4.15,0.832,5.664,2.348c1.514,1.514,2.348,3.524,2.348,5.663s-0.834,4.149-2.348,5.663L217.802,381.75
		c-1.51,1.512-3.52,2.344-5.66,2.344s-4.15-0.832-5.664-2.348L98.747,274.015c-1.514-1.514-2.348-3.524-2.348-5.663
		c0-2.138,0.834-4.149,2.351-5.667c1.51-1.512,3.52-2.344,5.66-2.344s4.15,0.832,5.664,2.348l96.411,96.411
		c1.5,1.5,3.535,2.343,5.657,2.343s4.157-0.843,5.657-2.343l234.849-234.849c3.125-3.125,3.125-8.189,0-11.314
		c-3.124-3.123-8.189-3.123-11.313,0L212.142,342.129l-90.75-90.751c-4.533-4.538-10.563-7.037-16.98-7.037
		s-12.448,2.499-16.978,7.034c-4.536,4.536-7.034,10.565-7.034,16.977c0,6.412,2.498,12.441,7.034,16.978l107.728,107.728
		c4.532,4.538,10.563,7.037,16.98,7.037c6.417,0,12.448-2.499,16.977-7.033l275.847-275.848c4.536-4.536,7.034-10.565,7.034-16.978
		S509.502,87.794,504.969,83.262z" />
            </g>
        </svg>
        <h1>Password Changed!</h1>
    </div>
    {% else %}

    <div class="form-box">
        <div class="change-password">
            <h2>Change Password</h2>
            <form method="post">
                {% if error_messages and error_messages.error %}
                <div class="error-message">{{ error_messages.error }}</div>
                {% endif %}
                <div class="input-box">
                    <!-- <span class="icon"><img src="password.png" /></span> -->
                    <input type="password" name="password1" required />
                    <label>Password</label>
                </div>
                {% if error_messages and error_messages.password1 %}
                <p class="input-error">{{ error_messages.password1 }}</p>
                {% endif %}
                <div class="input-box">
                    <!-- <span class="icon"><img src="password.png" /></span> -->
                    <input type="password" name="password2" required />
                    <label>Confirm Password</label>
                </div>
                {% if error_messages and error_messages.password2 %}
                <p class="input-error">{{ error_messages.password2 }}</p>
                {% endif %}
                <button type="submit" class="submit-button">Change Password</button>
            </form>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

templates/contact.html
{% extends 'base.html' %}
{% block title %}Login{% endblock %}

{% block content %}

<div class="content">
    <divs style="max-width: 600px; text-align: center; position: relative;">
        <h1>Contact</h1>
        <p style="padding-top: 20px;">
            Your feedback and inquiries are important to us! If you have any questions, suggestions, or just want to
            reach out, feel free to get in touch with us. You can contact us by sending an email to <a
                href="mailto:shubhamkumar101100@gmail.com">mailto:shubhamkumar101100@gmail.com</a>.
        </p><br>
        <p>We
            value your input and look forward to hearing from you. Whether it's about the "Memory Recall Challenge" or
            anything else, your communication is highly appreciated. We're here to ensure your experience is as
            enjoyable and seamless as possible. Don't hesitate to reach out we're just an email away!
        </p>
</div>

</div>
{% endblock %}

templates/forget-password.html
{% extends 'base.html' %}
{% block title %}Forget Password{% endblock %}

{% block content %}
<div class="form-page">
    {% if email_sent %}
    <div class="form-success">
        <svg fill="#000000" class="icon" version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg"
            xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 512 512" xml:space="preserve">
            <g>
                <path d="M474.045,173.813c-4.201,1.371-6.494,5.888-5.123,10.088c7.571,23.199,11.411,47.457,11.411,72.1
		c0,62.014-24.149,120.315-68,164.166s-102.153,68-164.167,68s-120.316-24.149-164.167-68S16,318.014,16,256
		S40.149,135.684,84,91.833s102.153-68,164.167-68c32.889,0,64.668,6.734,94.455,20.017c28.781,12.834,54.287,31.108,75.81,54.315
		c3.004,3.239,8.066,3.431,11.306,0.425c3.24-3.004,3.43-8.065,0.426-11.306c-23-24.799-50.26-44.328-81.024-58.047
		C317.287,15.035,283.316,7.833,248.167,7.833c-66.288,0-128.608,25.813-175.48,72.687C25.814,127.392,0,189.712,0,256
		c0,66.287,25.814,128.607,72.687,175.479c46.872,46.873,109.192,72.687,175.48,72.687s128.608-25.813,175.48-72.687
		c46.873-46.872,72.687-109.192,72.687-175.479c0-26.332-4.105-52.26-12.201-77.064
		C482.762,174.736,478.245,172.445,474.045,173.813z" />
                <path d="M504.969,83.262c-4.532-4.538-10.563-7.037-16.98-7.037s-12.448,2.499-16.978,7.034l-7.161,7.161
		c-3.124,3.124-3.124,8.189,0,11.313c3.124,3.123,8.19,3.124,11.314-0.001l7.164-7.164c1.51-1.512,3.52-2.344,5.66-2.344
		s4.15,0.832,5.664,2.348c1.514,1.514,2.348,3.524,2.348,5.663s-0.834,4.149-2.348,5.663L217.802,381.75
		c-1.51,1.512-3.52,2.344-5.66,2.344s-4.15-0.832-5.664-2.348L98.747,274.015c-1.514-1.514-2.348-3.524-2.348-5.663
		c0-2.138,0.834-4.149,2.351-5.667c1.51-1.512,3.52-2.344,5.66-2.344s4.15,0.832,5.664,2.348l96.411,96.411
		c1.5,1.5,3.535,2.343,5.657,2.343s4.157-0.843,5.657-2.343l234.849-234.849c3.125-3.125,3.125-8.189,0-11.314
		c-3.124-3.123-8.189-3.123-11.313,0L212.142,342.129l-90.75-90.751c-4.533-4.538-10.563-7.037-16.98-7.037
		s-12.448,2.499-16.978,7.034c-4.536,4.536-7.034,10.565-7.034,16.977c0,6.412,2.498,12.441,7.034,16.978l107.728,107.728
		c4.532,4.538,10.563,7.037,16.98,7.037c6.417,0,12.448-2.499,16.977-7.033l275.847-275.848c4.536-4.536,7.034-10.565,7.034-16.978
		S509.502,87.794,504.969,83.262z" />
            </g>
        </svg>
        <h1>Email sent successfully!</h1>
    </div>
    {% else %}
    <div class="form-box">
        <h2>Forget Password?</h2>
        <form method="post">
            {% if error_messages and error_messages.error %}
            <div class="error-message">{{ error_messages.error }}</div>
            {% else %}
            <span class="info">Enter your email here, and we'll send you a link to reset it.</span>
            {% endif %}
            <div class="input-box">
                <input type="email" name="email" required />
                <label>Email</label>
            </div>
            {% if error_messages %}{% if error_messages.email %}
            <p class="input-error">{{ error_messages.email }}</p>
            {% endif %}{% endif %}
            <button type="submit" class="submit-button">Submit</button>
        </form>
        {% endif %}
    </div>
</div>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% block title %}Playground{% endblock %}

{% block content %}
<div class="main">
  <div class="leaderboard">
    <div class="title">
      <h2>Leaderboard</h2>
    </div>
    {% if top3users %}
    <div class="top-users">
      <div class="user-details">
        <img class="user-photo"
          src="{% if top3users[1].profile_picture %}{{ top3users[1].profile_picture }}{% else %}{{ url_for('static', filename='assets/default-profile.png')}}{% endif %}">
        <p class="user-name">{{ top3users[1].name }}</p>
        <p class="user-score">Score: {{ top3users[1].high_score }}</p>
      </div>
      <div class="user-details" style="margin-bottom: 18px;">
        <img class="user-photo"
          src="{% if top3users[0].profile_picture %}{{ top3users[0].profile_picture }}{% else %}{{ url_for('static', filename='assets/default-profile.png')}}{% endif %}"
          style="width: 100px; height: 100px;">
        <p class="user-name">{{ top3users[0].name }}</p>
        <p class="user-score">Score: {{ top3users[0].high_score }}</p>
      </div>
      <div class="user-details">
        <img class="user-photo"
          src="{% if top3users[2].profile_picture %}{{ top3users[2].profile_picture }}{% else %}{{ url_for('static', filename='assets/default-profile.png')}}{% endif %}">
        <p class="user-name">{{ top3users[2].name }}</p>
        <p class="user-score">Score: {{ top3users[2].high_score }}</p>
      </div>
    </div>
    {% else %}
    <div style="height: 20px;"></div>
    {% endif %}
    <ul class="leaderboard-list">
      {% for user in users %}
      <li class="user-tile">
        <p class="user-rank">{{ loop.index }}</p>
        <img class="user-photo"
          src="{% if user.profile_picture %}{{ user.profile_picture }}{% else %}{{ url_for('static', filename='assets/default-profile.png')}}{% endif %}">
        <div class="column">
          <p class="user-name">{{ user.name }}</p>
          <p class="user-score">Score: {{ user.high_score }}</p>
        </div>
      </li>
      {% endfor %}
    </ul>

  </div>
  <div class="playground">
    <div class="">
      <h2 class="score-board">Welcome! Press start button to play.</h2>
      <div class="game-area">
        <div class="line-one">
          <div class="color-box red" type="button" id="red" onclick="submitColor('RED')"></div>
          <div class="color-box yellow" type="button" id="yellow" onclick="submitColor('YELLOW')"></div>
        </div>
        <div class="line-two">
          <div class="color-box purple" type="button" id="purple" onclick="submitColor('PURPLE')"></div>
          <div class="color-box green" type="button" id="green" onclick="submitColor('GREEN')"></div>
        </div>
      </div>
      <div class="action-buttons">
        <span class='game-action-start-btn' onclick="startGame()">Start Game</span>
        <span class='game-action-cancel-btn' onclick="cancelGame()">Cancel</span>
        <span class='game-action-restart-btn' onclick="restartGame()">Restart</span>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block scripts %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.0.1/socket.io.js"
  integrity="sha512-q/dWJ3kcmjBLU4Qc47E4A9kTB4m3wuTY7vkFJDTZKjTs8jhyGQnaUrxa0Ytd0ssMZhbNua9hE+E7Qv1j+DyZwA=="
  crossorigin="anonymous"></script>
<script type="text/javascript" charset="utf-8">
  let socket = null;
  let user_seq = [];
  let current_level = 1;

  function startGame() {
    document.getElementsByClassName('game-action-start-btn')[0].style.display = "none";
    socket = io();
    socket.on('message', function (data) {
      if (data['game_status'] == 'start') {
        document.getElementsByClassName('score-board')[0].innerHTML = 'Score: 0'
        blinkColorBox(data['new_color'])
      }
      else if (data['game_status'] == 'level_up') {
        current_level = data['current_level'];
        document.getElementsByClassName('score-board')[0].innerHTML = `Scrore: ${current_level - 1}`
        blinkColorBox(data['new_color'])
      }
      else if (data['game_status'] == 'game_over') {
        document.getElementsByClassName('score-board')[0].innerHTML = `Game Over! Your score is ${current_level - 1}`
        document.getElementsByClassName('game-action-cancel-btn')[0].style.display = "inline-block";
        document.getElementsByClassName('game-action-restart-btn')[0].style.display = "inline-block";
        user_seq = [];
        current_level = 1;
      }
    })
  }

  function submitColor(color) {
    if (socket != null) {
      user_seq.push(color)
      if (user_seq.length == current_level) {
        socket.emit('submit_colors', user_seq)
        user_seq = []
      }
    }
  }

  function blinkColorBox(color_name) {
    let a = document.getElementsByClassName(`color-box ${color_name.toLowerCase()}`)[0];
    a.classList.add('flash')
    setTimeout(function () { a.classList.remove('flash') }, 100);
  }

  function cancelGame() {
    document.getElementsByClassName('score-board')[0].innerHTML = 'Welcome! Press start button to play.'
    document.getElementsByClassName('game-action-start-btn')[0].style.display = "inline-block";
    document.getElementsByClassName('game-action-cancel-btn')[0].style.display = "none";
    document.getElementsByClassName('game-action-restart-btn')[0].style.display = "none";
    socket.close()
  }

  function restartGame() {
    document.getElementsByClassName('game-action-start-btn')[0].style.display = "none";
    document.getElementsByClassName('game-action-cancel-btn')[0].style.display = "none";
    document.getElementsByClassName('game-action-restart-btn')[0].style.display = "none";
    startGame()
  }

</script>

{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% block title %}Login{% endblock %}

{% block content %}

<div class="form-page">
    <div class="form-box">
        <div class="login">
            <h2>Login</h2>
            <form method="post">
                {% if error_messages and error_messages.error %}
                <div class="error-message">{{ error_messages.error }}</div>
                {% endif %}
                <div class="input-box">
                    <!-- <span class="icon"><img src="email.png" /></span> -->
                    <input type="email" name="email" required />
                    <label>Email</label>
                </div>
                {% if error_messages and error_messages.email %}
                <p class="input-error">{{ error_messages.email }}</p>
                {% endif %}
                <div class="input-box">
                    <!-- <span class="icon"><img src="password.png" /></span> -->
                    <input type="password" name="password" required />
                    <label>Password</label>
                </div>
                {% if error_messages and error_messages.password %}
                <p class="input-error">{{ error_messages.password }}</p>
                {% endif %}
                <div class="forget-password-text">
                    <a href="{{ url_for('route.forget_password') }}">Forget Password?</a>
                </div>
                <button type="submit" class="submit-button">Log in</button>
            </form>
            <form method="post">
                <input type="submit" class="submit-button-outline" value="Guest Login" , name="skip-login">
            </form>
            <div class="login-register-link">
                <p>
                    Don't have an account
                    <a href="{{ url_for('route.register') }}">Register</a>
                </p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/register.html
{% extends 'base.html' %}
{% block title %}Register{% endblock %}

{% block content %}

<div class="form-page">
    <div class="form-box">
        <div class="register">
            <h2>Register</h2>
            <form method="post">
                {% if error_messages and error_messages.error %}
                <div class="error-message">{{ error_messages.error }}</div>
                {% endif %}
                <div class="input-box">
                    <!-- <span class="icon"><img src="email.png" /></span> -->
                    <input type="name" name="name" required />
                    <label>Name</label>
                </div>
                {% if error_messages and error_messages.name %}
                <p class="input-error">{{ error_messages.name }}</p>
                {% endif %}
                <div class="input-box">
                    <!-- <span class="icon"><img src="email.png" /></span> -->
                    <input type="email" name="email" required />
                    <label>Email</label>

                </div>
                {% if error_messages and error_messages.email %}
                <p class="input-error">{{ error_messages.email }}</p>
                {% endif %}
                <div class="input-box">
                    <!-- <span class="icon"><img src="password.png" /></span> -->
                    <input type="password" name="password" required />
                    <label>Password</label>
                </div>
                {% if error_messages and error_messages.password %}
                <p class="input-error">{{ error_messages.password }}</p>
                {% endif %}
                <button type="submit" class="submit-button">Register</button>
            </form>
            <div class="login-register-link">
                <p>
                    Already have an account?
                    <a href="{{ url_for('route.login') }}">Login</a>
                </p>
            </div>
        </div>
    </div>
</div>
{% endblock %}